-- Migration 008: One-time balance sync only.
-- All triggers originally planned here have been removed:
--
--  * trg_wallets_balance_after_insert/update/delete
--    Removed: balance is managed atomically in the service layer.
--    Having both causes double-update.
--
--  * trg_transactions_transfer_check_ins/upd
--    Removed: @capacitor-community/sqlite on Android cannot execute
--    CREATE TRIGGER...BEGIN...END blocks reliably (incomplete input error).
--    Equivalent validation is enforced in transaction.schema.ts.
--
-- This migration is now intentionally statement-free. Older web SQLite
-- engines can fail on correlated UPDATE subqueries that reference wallets.id.
-- Wallet balances are maintained by the service layer.
