-- Migration 018: intentionally statement-free.
-- The previous data cleanup used self-join aliases with dotted id references,
-- which can fail in the Capacitor SQLite Web migration path. Runtime budget
-- writes now enforce the single-active-budget rule.
