-- Migration 021: intentionally statement-free.
-- This migration used to remove old placeholder wallets, but Capacitor SQLite
-- Web can fail on DELETE statements in the migration execute path with
-- "near id: syntax error". Keeping harmless placeholder wallets is preferable
-- to blocking app initialization.
